#!/bin/sh
#參考vgod改的

#安裝oh my zsh
curl -L http://install.ohmyz.sh | sh

#設定zsh-syntax-highlighting外掛
cd ~/.oh-my-zsh/custom/plugins
git clone git://github.com/zsh-users/zsh-syntax-highlighting.git

#設定.zshrc 捷徑
cd ~
git clone 這邊要放我的zshrc路徑
ln -s ~/.vim/zshrc ~/.zshrc
